### ISSUE TITLE
Looks like a bug in Stochastic_Embedding line 62

### ISSUE THREAD

**Issue by qwer1304** [LucaHermes/DeepView#2]
Hi,

Terrific tool!

Looks like there's a bug in Stochastic_Embedding.py on line 62:
It says    dist += (y_[k,j]-s_[i,j])**2
But i hasn't been set in this loop and the rest of the indexing is done with samp, so I guess it's a copy and paste error and it should have been dist += (y_[k,j]-s_[samp,j])**2 

Please advise,
David

PS I ported the package (without torch/tensorflow demos to Matlab. Works like a charm, :). (I'm an old-school guy ;))

**Comment by LucaHermes** [comment]
Hi!

Thank you for your comment and for opening this issue!
I will look into this tomorrow, as I am currently setting up my new system.
And you are probably right, although I think the correct index should be ```nn_[k,samp]``` instead of ```samp```.
As my tests are all passing, could you maybe validate if this solves your issue or provide an example where it fails?

Thank you very much :)

**Comment by qwer1304** [comment]
This is something I noticed during code reading:
The first loop on lines 47-56 has:

> _i_ = nn_[k,samp]

and then uses _i_ as in

> dist += (x_[k,j]-r_[_i_,j])**2

The second loop on lines 59-65 does **not** initialize _i_, but on line 62 has

> dist += (y_[k,j]-s_[_i_,j])**2

and then on lines 63-64 uses _samp_ where previously it has used _i_

> logv_i = -dist/sigma_[_samp_]
> w_i = w_[_samp_]

This jus doesn't make sense, so I was wondering whether _i_ should be replaced with _samp_, or the loop should be made as the first one (initialize _i_ and then replace references to _samp_ to _i_)

**Comment by LucaHermes** [comment]
Right, this does not make a lot of sense there. 
Looks like the ```StochasticEmbedding.py``` could use a general refactoring.
Unfortunately, this is the only class that was not written by me, so I have to dig a bit deeper into the mechanism. I am not completely sure yet what the correct fix for this code fragment would be, sorry.

**Comment by qwer1304** [comment]
By comparing to compute_H__(), it probably should be:

>         for samp in range(n_samps):
>             i = nn_[k,samp]
>             dist = 0
>             for j in range(n_dim):
>                 dist += (y_[k,j]-s_[i,j])**2
>             logv_i = -dist/sigma_[i]
>             w_i = w_[samp] # w_i was computed for i above
>             H_[k] += w_i*logv_i + (1-w_i)*(1-np.exp(logv_i))

**Comment by LucaHermes** [comment]
Right, this is also what I meant with my first response
> And you are probably right, although I think the correct index should be nn_[k,samp] instead of samp.

I will validate this and update the code.

**Comment by qwer1304** [comment]
Great! Thanx.
While you're at this, could you please also take a look at line 138

> logv_i = -dist/sigma_[samp]

IMHO, it should be

> logv_i = -dist/sigma_[i]

**Comment by LucaHermes** [comment]
All right, I am currently in touch with the author of the DeepView-paper and we will ultimately refactor the whole class. The small fixes will be applied first.
Thank you once again for pointing these out!
